### ISSUE TITLE
Error at refreshing Token

### ISSUE THREAD

**Issue by nightfreak** [Loxone/lxcommunicator#10]
I am using lxcommunicator without any changes. After 1 day running fine I always get the following error:

```
TokenHandler    TokenCommand failed! jdev/sys/refreshjwt/%s/%s
Could not refresh the token of 'chris' with permission + UNDEFINED, APP, OP_MODES, AUTOPILOT, EXPERT_MODE_LIGHT
{"LL":{"control":"dev/sys/refreshjwt","value":"File not found!","Code":"404"}}
Invalid/Outdated token - kill it!
2002
TokenHandler    TokenCommand failed! jdev/sys/killtoken/%s/%s
```
My Miniserver version is 9.1.10.30

**Comment by idoodler** [comment]
@nightfreak Hi, it looks like there is an issue with Miniservers running below `10.1.12.11` which is the version `JWT` were introduced.

Please try to replace the function '_getRefreshCommand' in 'TokenHandlerExt' with the following:

```
_getRefreshCommand: function _getRefreshCommand() {
    return FeatureCheck.check(FeatureCheck.feature.JWT_SUPPORT) ? Commands.TOKEN.REFRESH_JWT : Commands.TOKEN.REFRESH;
}
```

**Quick explanation:**
The commands are currently reversed, so if JWT is supported the non JWT command is used and vice versa.

**Comment by idoodler** [comment]
@nightfreak Please checkout the development branch, it includes a fix

**Comment by idoodler** [comment]
@nightfreak ping

**Comment by nightfreak** [comment]
Thanks, its solved!
