### ISSUE TITLE
Socket handshake/Connection with loxone miniserver via Argo/Cloudflare tunnel

### ISSUE THREAD

**Issue by qadirsuh** [Loxone/lxcommunicator#18]
Hello Guys.

Thank you for this amazing stuff. 

I have used this module and is working on local. i.e connecting my localhost server with my locally placed loxone miniserver i.e 192.168.xx.xx:8888 lxcommunicator works very well in this. I can send the commands and miniserver responds accordingly. here is the reponse

```
Successfully executed 'dev/sps/enablebinstatusupdate' with code 200 and value 1
type 2
event {
  uuid: '18b9e72a-01b9-27b4-ffff1f8a953ddb73',
  value: 6,
  toString: [Function: evToString]
}
event {
  uuid: '18b9e72a-01da-27c6-ffff1f8a953ddb73',
  value: 493,
  toString: [Function: evToString]
}
event {
  uuid: '18b9e72a-01e2-27c9-ffff1f8a953ddb73',
  value: 1435,
  toString: [Function: evToString]
}
event {
  uuid: '18b9e72b-0029-2a87-ffff1f8a953ddb73',
  value: 0,
  toString: [Function: evToString]
}....

```

Problem.
Now I have used Argo/Cloudflare tunnel as port forward and moved my Miniserver to internet. Now I can access the WebUI using this url i.e [https://lbgenetech-lxgenetech-dev.jamesbutler.ch/](https://lbgenetech-lxgenetech-dev.jamesbutler.ch/)

Problem is now socket communication isn't working. I am getting this error now.

```
WebSocket: ERROR: websocket error
WebSocket:  socket failed! WS Close Code: -unknown-
{ errorCode: 418 }
```

What could be the possible reason for this error?

I also tried setting the external address to [https://lbgenetech-lxgenetech-dev.jamesbutler.ch/](https://lbgenetech-lxgenetech-dev.jamesbutler.ch/) from loxone config

![image](https://user-images.githubusercontent.com/14326497/171614416-b717b26f-0693-4578-9dfb-ea978fbc3b02.png)

Still facing the same error

**Comment by LxToubey** [comment]
I think cloud flare doesn't support web sockets, [see doc](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/local-management/ingress/#supported-protocols).

**Comment by LxToubey** [comment]
For the current generation Miniservers I'd recommend using remote connect. 
For first generation, I cannot give a recommendation.

**Comment by qadir227** [comment]
@LxToubey we have first generation Miniserver :(
