### ISSUE TITLE
Encrypted command docs / examples

### ISSUE THREAD

**Issue by fodi** [Loxone/lxcommunicator#3]
First of all, thank you folks for already making my life easier with this library. However I'd like to ask for some more documentation or at least some examples on how to send encrypted commands to a Miniserver and process the encrypted response (returned by jdev/sys/enc) using this library. Thanks!

**Comment by LxToubey** [comment]
Glad to hear it helps. We'll ad samples for encrypted HTTP requests soon!

**Comment by eruecco87** [comment]
Any chance those examples are available now somewhere?
