### ISSUE TITLE
How to request LoxAPP3.json

### ISSUE THREAD

**Issue by Unluckymichell** [Loxone/lxcommunicator#30]
The included example code is wroking fine, connecting to the miniserver and reciving event information ist working.

But I cant figure out how to request the LoxAPP3.json file that includes the information about what uuid is what device.

The [Official Documentation](https://www.loxone.com/wp-content/uploads/datasheets/CommunicatingWithMiniserver.pdf) only tells me to send "data/LoxAPP3.json" to the miniserver. Doing this with socket.send results in nothing.

**Comment by quaddan** [comment]
Send command "data/LoxAPP3.json" to miniserver with your websocket connection and retrieve the result as text.

**Comment by Unluckymichell** [comment]
I figured it out myself as my project progressed. The documentation made it seem to me as if the LoxAPP3 also had to be fetched via the websocket connection.
But that wasn't right.

I have now implemented Lox App 3 via a GET on http://[MINISERVER]/data/LoxAPP3.json

This seems to be the correct way.
